[package]
name = "libchiaki"
version = "0.1.0"
edition = "2024"
description = "Safe Rust bindings for libchiaki (chiaki-ng's core library)"
authors = ["南浦月 <nanpuyue@gmail.com>"]
license = "AGPL-3.0-only"
links = "chiaki"

[features]
default = ["opus"]
opus = []

[build-dependencies]
bindgen = "0.72"
cc = "1"
pkg-config = "0.3"
